// TODO: 추후 서버 컴포넌트로 변환
"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DevTools } from "jotai-devtools";

import { usePathname } from "next/navigation";
import { AuthProvider } from "@/features/auth/model/AuthProvider";
import AuthButtons from "@/features/auth/ui/AuthButtons";
import { Toaster } from "sonner";
import Menu from "@/components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isVisible = !pathname.includes("login") && !pathname.includes("signup");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container mx-auto px-4 max-w-md`}
      >
        <AuthProvider>
          {isVisible && <AuthButtons />}

          <DevTools />
          {children}
          <Toaster />

          <Menu />
        </AuthProvider>
      </body>
    </html>
  );
}
