-- Phase 1A: Workout Hub foundational tables
-- programs, workout_sessions, workout_sets, pr_history, movement_aliases

-- ============================================================
-- programs
-- ============================================================
CREATE TABLE IF NOT EXISTS "public"."programs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    "title" text,
    "raw_notation" text NOT NULL,
    "parsed_data" jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE "public"."programs" IS '파싱된 프로그램 템플릿';

CREATE INDEX "programs_user_created_idx"
    ON "public"."programs" ("user_id", "created_at" DESC);

ALTER TABLE "public"."programs" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable users to view their own data only" ON "public"."programs"
    FOR SELECT TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable insert for users based on user_id" ON "public"."programs"
    FOR INSERT TO "authenticated"
    WITH CHECK ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable update for users based on user_id" ON "public"."programs"
    FOR UPDATE TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"))
    WITH CHECK ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."programs"
    FOR DELETE TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"));

GRANT ALL ON TABLE "public"."programs" TO "anon";
GRANT ALL ON TABLE "public"."programs" TO "authenticated";
GRANT ALL ON TABLE "public"."programs" TO "service_role";


-- ============================================================
-- workout_sessions
-- ============================================================
CREATE TABLE IF NOT EXISTS "public"."workout_sessions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    "program_id" bigint REFERENCES "public"."programs"("id") ON DELETE SET NULL,
    "session_date" date NOT NULL DEFAULT current_date,
    "daily_note" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE "public"."workout_sessions" IS '운동 세션 (하루 단위)';

CREATE INDEX "workout_sessions_user_date_idx"
    ON "public"."workout_sessions" ("user_id", "session_date" DESC);
CREATE INDEX "workout_sessions_program_idx"
    ON "public"."workout_sessions" ("program_id");

ALTER TABLE "public"."workout_sessions" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable users to view their own data only" ON "public"."workout_sessions"
    FOR SELECT TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable insert for users based on user_id" ON "public"."workout_sessions"
    FOR INSERT TO "authenticated"
    WITH CHECK ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable update for users based on user_id" ON "public"."workout_sessions"
    FOR UPDATE TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"))
    WITH CHECK ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."workout_sessions"
    FOR DELETE TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"));

GRANT ALL ON TABLE "public"."workout_sessions" TO "anon";
GRANT ALL ON TABLE "public"."workout_sessions" TO "authenticated";
GRANT ALL ON TABLE "public"."workout_sessions" TO "service_role";


-- ============================================================
-- workout_sets
-- ============================================================
CREATE TABLE IF NOT EXISTS "public"."workout_sets" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "session_id" bigint NOT NULL REFERENCES "public"."workout_sessions"("id") ON DELETE CASCADE,
    "exercise_order" int NOT NULL,
    "set_number" int NOT NULL,
    "movement_name" text NOT NULL,
    "prescribed_weight" numeric,
    "actual_weight" numeric,
    "status" text NOT NULL CHECK ("status" IN ('completed', 'failed', 'skipped')),
    "is_pr_attempt" boolean NOT NULL DEFAULT false,
    "note" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE "public"."workout_sets" IS '세트 단위 로그';

CREATE INDEX "workout_sets_session_idx"
    ON "public"."workout_sets" ("session_id");

ALTER TABLE "public"."workout_sets" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable users to view their own data only" ON "public"."workout_sets"
    FOR SELECT TO "authenticated"
    USING (EXISTS (
        SELECT 1 FROM "public"."workout_sessions" s
        WHERE s."id" = "workout_sets"."session_id"
          AND s."user_id" = ( SELECT "auth"."uid"() )
    ));

CREATE POLICY "Enable insert for users based on user_id" ON "public"."workout_sets"
    FOR INSERT TO "authenticated"
    WITH CHECK (EXISTS (
        SELECT 1 FROM "public"."workout_sessions" s
        WHERE s."id" = "workout_sets"."session_id"
          AND s."user_id" = ( SELECT "auth"."uid"() )
    ));

CREATE POLICY "Enable update for users based on user_id" ON "public"."workout_sets"
    FOR UPDATE TO "authenticated"
    USING (EXISTS (
        SELECT 1 FROM "public"."workout_sessions" s
        WHERE s."id" = "workout_sets"."session_id"
          AND s."user_id" = ( SELECT "auth"."uid"() )
    ))
    WITH CHECK (EXISTS (
        SELECT 1 FROM "public"."workout_sessions" s
        WHERE s."id" = "workout_sets"."session_id"
          AND s."user_id" = ( SELECT "auth"."uid"() )
    ));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."workout_sets"
    FOR DELETE TO "authenticated"
    USING (EXISTS (
        SELECT 1 FROM "public"."workout_sessions" s
        WHERE s."id" = "workout_sets"."session_id"
          AND s."user_id" = ( SELECT "auth"."uid"() )
    ));

GRANT ALL ON TABLE "public"."workout_sets" TO "anon";
GRANT ALL ON TABLE "public"."workout_sets" TO "authenticated";
GRANT ALL ON TABLE "public"."workout_sets" TO "service_role";


-- ============================================================
-- pr_history
-- ============================================================
CREATE TABLE IF NOT EXISTS "public"."pr_history" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    "exercise_id" bigint NOT NULL REFERENCES "public"."exercises"("id") ON DELETE RESTRICT,
    "previous_weight" numeric,
    "new_weight" numeric NOT NULL,
    "pr_date" date NOT NULL DEFAULT current_date,
    "note" text,
    "source" text NOT NULL CHECK ("source" IN ('manual', 'auto_detected_from_workout')),
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE "public"."pr_history" IS 'PR 변경 이력 (수동 + 자동감지)';

CREATE INDEX "pr_history_user_exercise_date_idx"
    ON "public"."pr_history" ("user_id", "exercise_id", "pr_date" DESC);

ALTER TABLE "public"."pr_history" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable users to view their own data only" ON "public"."pr_history"
    FOR SELECT TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable insert for users based on user_id" ON "public"."pr_history"
    FOR INSERT TO "authenticated"
    WITH CHECK ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable update for users based on user_id" ON "public"."pr_history"
    FOR UPDATE TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"))
    WITH CHECK ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."pr_history"
    FOR DELETE TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"));

GRANT ALL ON TABLE "public"."pr_history" TO "anon";
GRANT ALL ON TABLE "public"."pr_history" TO "authenticated";
GRANT ALL ON TABLE "public"."pr_history" TO "service_role";


-- ============================================================
-- movement_aliases
-- ============================================================
CREATE TABLE IF NOT EXISTS "public"."movement_aliases" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    "alias" text NOT NULL,
    "exercise_id" bigint NOT NULL REFERENCES "public"."exercises"("id") ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE "public"."movement_aliases" IS '표기 → 캐노니컬 운동 종목 매핑';

CREATE UNIQUE INDEX "movement_aliases_user_alias_lower_idx"
    ON "public"."movement_aliases" ("user_id", lower("alias"));

CREATE INDEX "movement_aliases_exercise_idx"
    ON "public"."movement_aliases" ("exercise_id");

ALTER TABLE "public"."movement_aliases" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable users to view their own data only" ON "public"."movement_aliases"
    FOR SELECT TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable insert for users based on user_id" ON "public"."movement_aliases"
    FOR INSERT TO "authenticated"
    WITH CHECK ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable update for users based on user_id" ON "public"."movement_aliases"
    FOR UPDATE TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"))
    WITH CHECK ((( SELECT "auth"."uid"() ) = "user_id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."movement_aliases"
    FOR DELETE TO "authenticated"
    USING ((( SELECT "auth"."uid"() ) = "user_id"));

GRANT ALL ON TABLE "public"."movement_aliases" TO "anon";
GRANT ALL ON TABLE "public"."movement_aliases" TO "authenticated";
GRANT ALL ON TABLE "public"."movement_aliases" TO "service_role";
